services:
  web:
    image: php:apache
    container_name: basic_apache_php
    ports:
      - "8080:80" 
    volumes:
      - ./html:/var/www/html
      - ./server-name.conf:/etc/apache2/conf-enabled/server-name.conf
    restart: unless-stopped
