services:
  web:
    image: php:apache
    container_name: basic_apache_php
    ports:
      # CHANGED: Host port 8080 -> Container port 80
      - "8080:80" 
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
