services:
  web:
    image: httpd:latest
    container_name: basic_apache_php
    ports:
    - '8080:80'
    volumes:
    - ./html:/usr/local/apache2/htdocs
    # 🌟 NEW: Mount server-name.conf over the httpd-vhosts.conf file, 
    # which is included by the default httpd.conf
    - ./server-name.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf 
    
    environment:
      # This env var is now optional, as ServerName is hardcoded in the conf file
      APACHE_SERVER_NAME: ${APACHE_SERVER_NAME} 
      
    restart: unless-stopped
