services:
  web:
    image: httpd:latest
    container_name: basic_apache_php
    ports:
    - '8080:80'
    volumes:
    - ./html:/usr/local/apache2/htdocs
    # 🌟 Mount the custom config file over the main one (or where it's included)
    - ./httpd-custom.conf:/usr/local/apache2/conf/httpd.conf
   
    # 🌟 NUEVO: Pasa la variable de Dokploy al contenedor
    environment:
      # Dokploy sustituirá ${APACHE_SERVER_NAME} por su valor
      APACHE_SERVER_NAME: ${APACHE_SERVER_NAME} 
      
    # volumes:
      #- ./html:/var/www/html
      # 🌟 NUEVO: Monta el archivo de configuración en un lugar que Apache lee
      # - ./server-name.conf:/etc/apache2/conf-enabled/server-name.conf
      
    restart: unless-stopped
